//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDTomeOfKeeping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public int CampaignID { get; set; }
        public string DMUserID { get; set; }
        public string CampaignName { get; set; }
        public int CharacterIDs { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Character Character { get; set; }
    }
}
